### ISSUE TITLE
Comment: Getting started (guides/basics/starting.md)

### ISSUE THREAD

**Issue by RalfDetzler** [feathersjs/docs#1036]
When I follow the setup instructions

`npm install @feathersjs/feathers --save`

I am getting error message "npm ERR! Cannot read property 'startsWith' of null". 

The logfile:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@feathersjs/feathers',
1 verbose cli   '--save' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 72f53af4cdb11c3a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for @feathersjs/feathers@latest Cannot read property 'startsWith' of null
8 verbose stack TypeError: Cannot read property 'startsWith' of null
8 verbose stack     at getProxy (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/agent.js:164:25)
8 verbose stack     at getAgent (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/agent.js:37:19)
8 verbose stack     at remoteFetch (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/index.js:310:17)
8 verbose stack     at opts.cacheManager.match.then.res (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/index.js:172:14)
8 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
8 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
8 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
8 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
8 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
8 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
8 verbose stack     at Promise._resolveCallback (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:432:57)
8 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:524:17)
8 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
8 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
8 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
8 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
9 verbose cwd /home/vagrant/dev/tmp/feathers-basics
10 verbose Linux 3.13.0-139-generic
11 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "@feathersjs/feathers" "--save"
12 verbose node v8.9.4
13 verbose npm  v5.6.0
14 error Cannot read property 'startsWith' of null
15 verbose exit [ 1, true ]

I am working on Ubuntu

`lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
`

Best regards
Ralf
-----------
Update: seems to be a general npm issue.

**Comment by RalfDetzler** [comment]
Sorry, was a problem with the proxy setting for npm. No Feathers issue.
