### ISSUE TITLE
Comment: Building a frontend (guides/chat/frontend.md)

### ISSUE THREAD

**Issue by shyamvkansagra** [feathersjs/docs#1046]
I followed all the steps mentioned in the documentation till this page, but still it throws the below error for me:

 ```
return async context => {
               ^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\SOMETHING\SOMETHING\feathers-chat-app\feathers-chat\src\services\messages\messages.hooks.js:3:24)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! my-chat-app@0.0.0 start: `node src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-chat-app@0.0.0 start script 'node src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-chat-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-chat-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-chat-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\SOMETHING\SOMETHIN\feathers-chat-app\feathers-chat\npm-debug.log
```

I am trying ```npm start``` to run the project on localhost but it is not working.

**Comment by daffl** [comment]
As mentioned in the [prerequesites section of the guide](https://docs.feathersjs.com/guides/basics/setup.html#prerequisites), your `node --version` has to show `8.0.0` or later for the examples to work. The easiest way to manage multiple versions of node in Linux and Mac OS is via [nvm](https://github.com/creationix/nvm).
