### ISSUE TITLE
Comment: Writing tests (guides/chat/testing.md)

### ISSUE THREAD

**Issue by wgmyers** [feathersjs/docs#1220]
### Comment/Problem

Cannot get `client-users.test.js` to work.

Socket times out, and tests don't run at all; both `before-all` and `after-all` hooks fail.

Wrapping the `await client authenticate` call in `makeClient` in a try/catch block fixes some of this and at least gets the first of the three tests (registering the service) to run and pass, but both other tests persistently time out.

Also, not sure I understand the point of that `await client authenticate` call as it is not explicitly a test. Perhaps this could be more clearly explained in the text.

**Comment by eddyystop** [comment]
I assume you meant users.service.client.js.

The before would fail if
- The server app could not be created. This can happen on Win10.
- The client app coul;s not be created. No such reports.
- The client app could not connect to the server app.
- The client app could not authenticate.

The after would fail with any of the above since the client cannot logout.

You have not provided enough info for me to be more specific.

The test very much depends on the environment.
- There are reports that Win10 does not run `delete require.cache[require.resolve('../../../src1/app')];     app = require('../../../src1/app');` correctly. Correctly being how Linux runs it successfully.
- The time it takes the client to connect and then to login depends on your setup. Double the `timeoutForStartingServerAndClient` and other timers in config/default.js..
- The environment starts to degrade and you have to recycle the OS. I run Unbuntu in a VM and, sooner or later, I start getting such errors. I need to restart the VM and often the OS.

Let me know what you find.

**Comment by wgmyers** [comment]
Thanks for getting back to me. My apologies for not being more specific.

I am referring to `client-users.test.js` as described on the page https://docs.feathersjs.com/guides/chat/testing.html and installed in the ```test/services``` directory as instructed.

I have been working steadily through the tutorial in the last weeks, installing everything as I go, so everything should be pretty much up to date. FWIW,  I am using Ubuntu 16.04, running node version 8.11.3, npm version 6.4.1 and feathers version 3.8.7. The node_modules directory for feathers-chat contains mocha 5.2.0 and both socket.io and socket-io.client 2.1.1.

Please let me know if there are any other details I should provide, or if it is already clear that I need to run some kind of update tool owing to breaking changes, clear to you, if not to me, from the version numbers above, that I have managed not to pick up.

When I run the client-users.test.js file using code directly copied and pasted from the page above, I get the following output from running npm test:

```
wayne@mymachine:~/src/js/feathers.js/tutorial/feathers-chat$ npm test

> feathers-tutorial-chat-app@0.0.0 test /home/wayne/src/js/feathers.js/tutorial/feathers-chat
> npm run eslint && npm run mocha


> feathers-tutorial-chat-app@0.0.0 eslint /home/wayne/src/js/feathers.js/tutorial/feathers-chat
> eslint src/. test/. --config .eslintrc.json --fix


> feathers-tutorial-chat-app@0.0.0 mocha /home/wayne/src/js/feathers.js/tutorial/feathers-chat
> npm run clean && NODE_ENV=test mocha test/ --recursive --exit


> feathers-tutorial-chat-app@0.0.0 clean /home/wayne/src/js/feathers.js/tutorial/feathers-chat
> shx rm -rf test/data/



  Feathers application tests
    ✓ starts and shows the index page (38ms)
    404
error: Page not found {"type":"FeathersError","name":"NotFound","code":404,"className":"not-found","data":{"url":"/path/to/nowhere"},"errors":{}}
      ✓ shows a 404 HTML page
error: Page not found {"type":"FeathersError","name":"NotFound","code":404,"className":"not-found","data":{"url":"/path/to/nowhere"},"errors":{}}
      ✓ shows a 404 JSON error without stack trace

  'gravatar' hook
    ✓ creates a gravatar link from the users email

  'populate-user' hook
    ✓ populates a new message with the user

  'process-message' hook
    ✓ processes the message as expected

  'users' service - client
Publishing all events to all authenticated users. See `channels.js` and https://docs.feathersjs.com/api/channels.html for more information.
Feathers application started on http://localhost:3030
    1) "before all" hook
    2) "after all" hook


  6 passing (6s)
  2 failing

  1) 'users' service - client
       "before all" hook:
     Error: Socket connection timed out
      at Timeout._onTimeout (node_modules/@feathersjs/client/dist/feathers.js:2386:18)

  2) 'users' service - client
       "after all" hook:
     TypeError: Cannot read property 'logout' of undefined
      at Context.after (test/services/client-user-test-test.js:29:12)



npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! feathers-tutorial-chat-app@0.0.0 mocha: `npm run clean && NODE_ENV=test mocha test/ --recursive --exit`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the feathers-tutorial-chat-app@0.0.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wayne/.npm/_logs/2018-11-04T13_27_26_981Z-debug.log
npm ERR! Test failed.  See above for more details.

```

I have temporarily removed the other services tests for clarity.

To be clear - this is the result of the code copied and pasted from the page. I initially typed it out by hand and diffed it against the copy/pasted version to ensure no typos; both versions give the same result.

The socket consistently fails to connect and times out.

Wrapping the ```await client authenticate``` call in ```makeClient``` in a try/catch block fixes some of this and at least gets the first of the three tests (registering the service) to run and pass, but both other tests - the ones that require the socket - persistently time out.

I will confess that I have not tried rebooting the machine and rerunning the code. I will try that now and report back.

**Comment by wgmyers** [comment]
I have just rebooted the machine and rerun npm test.

Output is identical to that above.

**Comment by wgmyers** [comment]
No worries.

**Comment by justin-fiedler** [comment]
@wgmyers I had the exact same errors on Windows 10. For me the solution was what @eddyystop mentioned about the require cache not being properly deleted. I discovered [require-nocache](https://github.com/ysulyma/require-nocache) that makes cache busting nice and easy. I updated my tests to include the 'app' module as follows and most of my problems went away.

```node
const requireNoCache = require('require-nocache')(module);
const app = requireNoCache('../../src/app');
```

Something else I ran into was that the server did not always close() successfully in after(). I believe this was due to lingering socket connections. For this problem I used [server-destroy](https://github.com/isaacs/server-destroy) which automatically tracks connections and destroys them via a convenient destroy() method.

```node
const enableDestroy = require('server-destroy');

// ...other imports, etc

describe('Feathers application tests', function () {
  before((done) => {
    this.server = app.listen(port);
    enableDestroy(this.server);

    // ...other before stuff
  });

  after((done) => {
    this.server.destroy(done);
  });

  // ...tests
}
```

Hope this helps you. Good luck.
