### ISSUE TITLE
App crashes suddenly with following 

### ISSUE THREAD

**Issue by ssh713** [feathersjs/docs#1261]
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at channel.connections.forEach.connection (/Users/az/temp-work/feathers-chat/node_modules/@feathersjs/transport-commons/lib/channels/channel/combined.js:11:18)
    at Array.forEach (<anonymous>)
    at children.forEach.channel (/Users/az/temp-work/feathers-chat/node_modules/@feathersjs/transport-commons/lib/channels/channel/combined.js:8:25)
    at Array.forEach (<anonymous>)
    at collectConnections (/Users/az/temp-work/feathers-chat/node_modules/@feathersjs/transport-commons/lib/channels/channel/combined.js:7:12)
    at new CombinedChannel (/Users/az/temp-work/feathers-chat/node_modules/@feathersjs/transport-commons/lib/channels/channel/combined.js:21:39)
    at Function.channel (/Users/az/temp-work/feathers-chat/node_modules/@feathersjs/transport-commons/lib/channels/mixins.js:49:14)
    at Function.channel (/Users/az/temp-work/feathers-chat/node_modules/@feathersjs/transport-commons/lib/channels/mixins.js:30:23)
    at Socket.socket.once (/Users/az/temp-work/feathers-chat/node_modules/@feathersjs/socketio/lib/index.js:71:23)

**Comment by daffl** [comment]
Please provide more information about the problem:

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:
