### ISSUE TITLE
Comment: Recipe: Basic OAuth (guides/auth/recipe.oauth-basic.md)

### ISSUE THREAD

**Issue by sripathij** [feathersjs/docs#992]
Thank you so much for the recipe. This really helps. I tried building on this by building an app that supports both the local strategy and Google login. In doing so, I get an error under a specific condition - **The application generates an access token for the first user to login using a google id. Subsequent users get the following error 

 error:  Conflict: email: null already exists.
    at new Conflict (D:\feathersTest\node_modules\@feathersjs\errors\lib\index.js:137:17)
    at errorHandler (D:\feathersTest\node_modules\feathers-mongoose\lib\error-handler.js:37:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)**

Tried troubleshooting this with little luck. It appears that mongoose is not able to insert a second social login user record but throws a conflict error incorrectly.

**Comment by sripathij** [comment]
Just wanted to add that the error shows up even if I generate authentication with only Google as the provider.

**Comment by sripathij** [comment]
Closed it as I realized the issues here have more to do with the documentation than feathers itself. Maybe the leave comment link on the docs should provide some context.
